rpmpm.cc (pkgRPMLibPM::Process): commented out unused code which breaks gcc-4.1
rpm/rpmpm.cc:932: error: jump to label ‘exit’
rpm/rpmpm.cc:791: error:   from here
rpm/rpmpm.cc:846: error:   crosses initialization of ‘int repackage’
rpm/rpmpm.cc:843: error:   crosses initialization of ‘int packagesTotal’